version: "3.8"
services:
  backend:
    build: ./backend  # Ensure this folder exists!
    container_name: e_shop_backend
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend  # Ensure this folder exists!
    container_name: e_shop_frontend
    ports:
      - "8080:80"
