name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [dev]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Image
        run: docker build -t backend-app ./backend

      - name: Build Frontend Image
        run: docker build -t frontend-app ./frontend

      - name: Run Backend Tests
        run: |
          cd backend && npm install && npm test

      - name: Run Frontend Tests
        run: |
          cd frontend && npm install && npm test

      - name: Security Scan (OWASP ZAP)
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'http://localhost'
